Impact Crater logic
randovania/randovania pull request #1012
Opened 2020-09-28 18:39 UTC by gollop

Doesn't update the human-readable version. The tricks component of the JSON is just echoes tricks with some echoes-exclusive tricks removed.

2020-09-28 19:50 UTC, henriquegemignani requested changes

2020-09-28 19:50 UTC, henriquegemignani commented on randovania/data/json_data/prime1.json
> +                                    "type": "and",
This is being a big and: `Power Beam and Ice Beam and Wave Beam and Plasma Beam and Missile ≥ 50 and Flamethrower and Charge Beam and Knowledge (Beginner)`

2020-09-28 19:50 UTC, henriquegemignani commented on randovania/data/json_data/prime1.json
> +                                    "type": "and",
this is being just a big "and": `Power Beam and Ice Beam and Wave Beam and Plasma Beam and Missile ≥ 50 and Flamethrower and Charge Beam and Knowledge (Beginner)`

2020-09-28 19:50 UTC, henriquegemignani commented on randovania/data/json_data/prime1.json
> +                            "dock_weakness_index": 1,
The dock_weakness_database has the same index for Ice/Wave/Plasma doors, so this is likely wrong :X

2020-11-02 21:32 UTC, gollop commented
UltiNaruto implemented no tricks logic for this, so closing.

2020-11-02 21:32 UTC, closed without merging