Prime 1 - Database Fixes
randovania/randovania pull request #2364
Opened 2021-11-25 01:07 UTC by toasterparty

2021-11-25 02:50 UTC, duncathan requested changes

2021-11-25 02:50 UTC, duncathan commented on randovania/data/migration_data.json
> +                "Event48": 48
this isn't necessary and should probably be reverted

2021-11-25 21:04 UTC, duncathan requested changes
There's no connection to Pickup - Spider Ball which is likely why the test is failing

2021-11-26 21:57 UTC, henriquegemignani commented
There has been some database format changes in main, you seem to have solved the merge conflicts in a not great way

2021-11-27 01:54 UTC, toasterparty commented
@henriquegemignani Did I resolve the conflicts okay?

2021-11-27 02:31 UTC, henriquegemignani commented
> @henriquegemignani Did I resolve the conflicts okay? Is the `codecov/project` thing my fault?

Seems ok. codecov weirdness when you update a branch. Also might just be a different db causing different flow in the app or whatever. There's not a perfect unit test style testing of some core logic stuff.

2021-11-27 02:49 UTC, duncathan commented
![image](https://user-images.githubusercontent.com/2979303/143665767-85db862b-d803-4ca0-afa7-e3ae4f633250.png)
I wouldn't worry about the coverage, given these lines being missed is probably a good thing

2021-11-28 19:18 UTC, merged