Added Spring Ball to Prime 1 patches
randovania/randovania pull request #2686
Opened 2022-01-31 19:06 UTC by UltiNaruto

2022-02-01 17:25 UTC, toasterparty requested changes

2022-02-01 17:25 UTC, toasterparty commented on randovania/games/prime1/presets/moderate_challenge.rdvpreset
> +        "spring_ball": false,
Rather than update the presets directly, implement a preset migration for this change (thus maintaining forward compatibility).

2022-02-01 17:25 UTC, toasterparty commented on randovania/games/prime1/patcher/randomprime_patcher.py
> +                "springBall": configuration.spring_ball,
Changes made here need to be reflected in the expected test output used by the randomprime patcher test.

2022-02-03 21:42 UTC, toasterparty requested changes

2022-02-03 21:42 UTC, toasterparty commented on randovania/gui/ui_files/preset_prime_patches.ui
> +              <string>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Restores the Spring Ball functionnality from Metroid Prime Trilogy.&lt;br/&gt;Use C-Stick Up while being morphed to use Spring Ball
> functionnality

2022-02-03 21:59 UTC, toasterparty commented
@UltiNaruto when you keep force pushing the same commit over and over, it makes it really hard for reviewers to only review the delta between their last review and the current HEAD. I'd prefer you to make incremental changes in the future once the PR is open.

2022-02-03 22:00 UTC, toasterparty approved these changes

2022-02-03 22:00 UTC, UltiNaruto commented
You mean like splitted commits?

2022-02-03 22:02 UTC, henriquegemignani commented
> @UltiNaruto when you keep force pushing the same commit over and over, it makes it really hard for reviewers to only review the delta between their last review and the current HEAD. I'd prefer you to make incremental changes in the future once the PR is open.

I actually learned today you can click the "force-pushed" text and it opens a diff for before and after the force push.

2022-02-03 22:06 UTC, toasterparty commented
> I actually learned today you can click the "force-pushed" text and it opens a diff for before and after the force push.

That makes things better. It's still preferred to not have forced pushed for two reasons:
1) I can see in the discussion/commits view what the reasons for each change is (via commit messages)
2) GitHub has a UI button for showing a diff of only things which have not yet been covered by your past review(s). This button does not appear when the commits are force-pushed.

2022-02-03 22:33 UTC, merged