Added DELTARUNE compatibility
randovania/randovania pull request #2796
Opened 2022-02-15 00:33 UTC by jonloveslegos

Added DELTARUNE (spelled with all caps)
- Randomizes items, key items, spells, weapons, armor, and starting abilities.

2022-02-15 20:22 UTC, henriquegemignani requested changes
I'll have some comments about the `patch_game` function later.

2022-02-15 20:22 UTC, henriquegemignani commented on randovania/games/deltarune/patcherfolder/__init__.py
> +            "hasSpoiler": description.has_spoiler,
`has_spoiler` to be consistent with the rest

2022-02-15 23:11 UTC, jonloveslegos commented
I made the requested changes

2022-02-24 22:29 UTC, duncathan requested changes
We've put a few refactors through that affect the game classes since you opened the PR. You'll need to apply those refactors to DELTARUNE when fixing the merge conflicts.

2022-02-24 22:29 UTC, duncathan commented on randovania/games/deltarune/patcherfolder/__init__.py
> +    def patch_game(self, input_file: Optional[Path], output_file: Path, patch_data: dict,
the majority of this function, as well as the `deltapatcher` folder you've added, should probably be in a separate repo and uploaded as a PyPi package for use with pip. if you need assistance getting this set up let us know in discord

2022-03-02 22:18 UTC, duncathan commented
Please resolve the conflicts

2022-03-15 18:11 UTC, henriquegemignani requested changes

2022-03-15 18:11 UTC, henriquegemignani commented on randovania.spec
> +                 ("deltapatcher", "deltapatcher"),
not needed, as this is handled by the extra package

2022-03-15 18:11 UTC, henriquegemignani commented on randovania/games/deltarune/game_data.py
> +    patcher=patcherfolder.PatcherMaker(),
This part has changed significantly in newer Randovania versions

2022-08-04 22:42 UTC, duncathan commented
it seems that progress on this has stalled. if work continues I will happily reopen the PR!

2022-08-04 22:42 UTC, closed without merging