Work towards a better introduction flow
randovania/randovania pull request #3571
Opened 2022-08-10 18:03 UTC by henriquegemignani

- Specific tab for Multiworld
- Introduction tab for each game
- Game generation is next to the introduction tab of each game

This new UI looks terrible because I haven't polished at all, but I want feedback on how it works.

2022-08-10 19:43 UTC, duncathan requested changes
on the functional side, I think the Introduction tab should include a button to generate a seed using the default preset for each game. that way absolute newcomers can just get right into it. obviously the aesthetics need some substantial improvements too lol

2022-08-10 19:43 UTC, duncathan commented on randovania/gui/lib/preset_tree_widget.py
> +        self.root_tree_item.setExpanded(True)
a comment here explaining the hack might be nice

2022-08-10 19:43 UTC, duncathan commented on randovania/gui/main_window.py
> +        # self.tab_create_seed.setup_ui(self, self, self._options)
if this is being commented, the log should be too

2022-08-10 20:13 UTC, henriquegemignani commented
> on the functional side, I think the Introduction tab should include a button to generate a seed using the default preset for each game. that way absolute newcomers can just get right into it. obviously the aesthetics need some substantial improvements too lol

I'm unsure how much of the introduction tab should be freestyle per game and how much we expect some things to allow for code sharing.

2022-08-11 19:05 UTC, duncathan reviewed
nothing seems immediately wrong

2022-08-12 00:03 UTC, duncathan approved these changes
lots of improvements yet to make, but I'm gonna go ahead and merge so we can start collecting feedback ASAP. some immediate things:
 - write text for TODOs
 - declutter the main window tabs. help, about, and changelog can probably all be moved to a dropdown menu
 - consider changing the game select in the Games tab from even more tabs to another method. three layers of tabs is a bit much imo
 - investigate aligning the flow layout somehow
 - rework the welcome tab
 - have the game cover images change when hovered, to indicate they're clickable

2022-08-12 00:04 UTC, merged