Dread: Ferenia revision (Complete except EMMI and Escue Zone)
randovania/randovania pull request #3642
Opened 2022-08-25 10:50 UTC by Hugoshido

- Made all Walljumps (Beginner) and some movement Trivial
- Updated some tricks to templates
- Added Speedbooster movement
- Added "Disable Door Rando" to cold room 
-

2022-08-25 16:01 UTC, XenoWars requested changes

2022-08-25 16:02 UTC, XenoWars commented
Quite a bit, though I would have preferred waiting until I did the IBJ changes as I've been saying in Discord.

2022-08-25 18:10 UTC, closed without merging

2022-08-26 05:12 UTC, Hugoshido commented on randovania/games/dread/json_data/Ferenia.txt
> +      Trivial
Yes you can just Walljump up there

2022-08-26 05:12 UTC, Hugoshido commented on randovania/games/dread/json_data/Ferenia.txt
> -              Knowledge (Beginner) and Lay Power Bomb
Check

2022-08-26 05:12 UTC, Hugoshido commented on randovania/games/dread/json_data/Ferenia.txt
> +              Grapple Beam and Disabled Door Lock Randomizer
Check

2022-08-26 05:13 UTC, Hugoshido commented on randovania/games/dread/json_data/Ferenia.txt
> +      Flash Shift and Speed Booster
The idea was the speedmethod going from there.. But I added it to the central platform instead

2022-08-26 05:13 UTC, Hugoshido commented on randovania/games/dread/json_data/Ferenia.txt
> +      Flash Shift or Speed Booster or Simple IBJ
Check

2022-08-26 05:13 UTC, Hugoshido commented on randovania/games/dread/json_data/Ferenia.txt
> +      Space Jump or Simple IBJ
Check

2022-08-26 05:13 UTC, Hugoshido commented on randovania/games/dread/json_data/Ferenia.txt
> +          Flash Shift or Spin Boost or Simple IBJ
Check

2022-08-26 05:13 UTC, Hugoshido commented on randovania/games/dread/json_data/Ferenia.txt
> +      Morph Ball
Check

2022-08-26 05:13 UTC, Hugoshido commented on randovania/games/dread/json_data/Ferenia.txt
> +          Movement (Beginner) and Simple IBJ
Check

2022-08-26 05:14 UTC, Hugoshido commented on randovania/games/dread/json_data/Ferenia.txt
> +      Flash Shift or Grapple Beam or Spider Magnet or Speed Booster or Simple IBJ or Use Spin Boost
Yes you can Walljump + Flashshift up there..

2022-08-26 05:15 UTC, Hugoshido commented on randovania/games/dread/json_data/Ferenia.txt
> +          Morph Ball and Speed Booster and Disabled Door Lock Randomizer
Check

2022-08-26 05:34 UTC, Hugoshido commented on randovania/games/dread/json_data/Ferenia.txt
>                Grapple Beam or Spider Magnet
You can just jump + flash to the ledge and then up to the ceiling

2022-08-26 05:48 UTC, Hugoshido commented on randovania/games/dread/json_data/Ferenia.txt
> +          Grapple Beam or Space Jump or Simple IBJ
Spin boost is enough to get up there

2022-08-26 06:02 UTC, Hugoshido commented on randovania/games/dread/json_data/Ferenia.txt
> +          Flash Shift or Simple IBJ or Use Spin Boost
Check