Dread: Remove requirement to have grapple to obtain Elun access pickup
randovania/randovania pull request #3774
Opened 2022-09-16 19:04 UTC by Tyranisaur

2022-09-16 19:15 UTC, XenoWars requested changes
Inaccurate. Grapple is required if you have not used the flipper. If it's simple enough to be trickless, you should change it to an Or listing either Grapple or (After Super Missile Rotatable and Shoot Super Missile) (something along that for the event name)

2022-09-16 19:23 UTC, Tyranisaur commented
Right I suppose that accuracy is required for things like elevator rando, different starting locations etc. Otherwise you normally need to flip the rotatable to have access to the super locked door anyway.

Also, if you open the super locked door from behind, does that break the super lock even without supers?

2022-09-16 19:24 UTC, XenoWars commented
> Also, if you open the super locked door from behind, does that break the super lock even without supers?

Well, the super lock is on both sides in rando. All door covers break on both sides when you break one of them.

2022-09-16 19:25 UTC, XenoWars commented
Might be possible to store a speed if the flipper isnt used?

2022-09-16 23:08 UTC, XenoWars requested changes

2022-09-16 23:08 UTC, XenoWars commented on randovania/games/dread/json_data/Ghavoran.txt
> +      Before Ghavoran - Super Missile Rotatable
Remove this. You can only access it after the flipper has been used. There's also no point in even having it as you can't go through it anyway

2022-09-16 23:08 UTC, XenoWars commented on CHANGELOG.md
> +- Changed: Allow traversal through the bottom of Ghavoran Flipper Room without flipping the spinner
This is already in the logic, so take this out.

2022-09-17 00:08 UTC, XenoWars commented
Probably just capitalize morph ball in the changelog and it's good.

2022-09-17 00:09 UTC, XenoWars approved these changes

2022-09-20 17:06 UTC, merged