Add Movement(Beginner) trick to Hall of Combat Mastery
randovania/randovania pull request #3905
Opened 2022-11-09 15:17 UTC by f-raZ0R

After breaking the HoCM tube, you can NSJ Screw to get enough distance to leave the portal.

2022-11-09 20:03 UTC, f-raZ0R commented
> Add an entry in the changelog.
> 
> Can you add a video for this?

Sure thing, does this look good?
Wasn't really sure what format you wanted the changelog addition to be in, as I couldn't find any documentation on it in the repo, so I just added onto it based on what was already there.

2022-11-09 20:18 UTC, dyceron commented
> > Add an entry in the changelog.
> > Can you add a video for this?
> 
> Sure thing, does this look good? Wasn't really sure what format you wanted the changelog addition to be in, as I couldn't find any documentation on it in the repo, so I just added onto it based on what was already there.

Streamable isn't really a reliable site for uploads since overtime they get deleted, unless you pay to have videos last longer.

2022-11-09 20:23 UTC, f-raZ0R commented
> 
> Streamable isn't really a reliable site for uploads since overtime they get deleted, unless you pay to have videos last longer.

What alternatives would you recommend?

2022-11-09 20:25 UTC, duncathan commented
YouTube.

2022-11-10 23:51 UTC, XenoWars requested changes

2022-11-10 23:51 UTC, XenoWars commented on CHANGELOG.md
> +
The entry should be moved under to the existing Echoes section that was added with Inverted Aether

2022-11-11 00:29 UTC, henriquegemignani approved these changes

2022-11-11 00:38 UTC, merged