Samus Returns - Initial prep for patcher support
randovania/randovania pull request #3999
Opened 2022-12-15 22:46 UTC by dyceron

- Add nothing item
- Removed unused templates
- Other internal updates

2023-06-11 05:58 UTC, ThanatosGit requested changes
This is just for passing tests

2023-06-11 05:58 UTC, ThanatosGit commented on randovania/games/samus_returns/gui/__init__.py
>      preset_tabs,
You named that `msr_preset_tabs` in the meantime

2023-06-11 05:58 UTC, ThanatosGit commented on randovania/games/samus_returns/exporter/patch_data_factory.py
> +from randovania.game_description.world.node import Node
All these imports of `randovania.game_description.world......` moved to `randovania.game_description.db....` 
Also`world` was renamed to `region`.
Please rename also the variables

2023-06-11 05:58 UTC, ThanatosGit commented on randovania/games/samus_returns/exporter/patch_data_factory.py
> +            return self.game.world_list.node_by_identifier(identifier)
e.g. this is now `region_list` at probably many more usages of world are in here

2023-06-13 09:32 UTC, henriquegemignani requested changes
Please test `MSRPatchDataFactory.create_data`.

Look at test_dread_patch_data_factory and test_create_patch_data there for a sample code.
You'll have to generate a RDVGame, add to test files folder and then also add the expected patch_data.json

2023-07-01 22:33 UTC, closed without merging