Dread April Fool's 2023
randovania/randovania pull request #4234
Opened 2023-03-29 01:40 UTC by ArcanoxDragon

This is ridiculously goofy, but if it's sane enough (and _soon_ enough) to be accepted, I'd be honored 😅

It simply replaces the item location template used for Dread's hint messages with a reference to the ["it goes in the square hole" meme](https://www.youtube.com/watch?v=Nz8ssH7LiB0) on April Fool's Day. The hints read something along the lines of `Can you guess where [the item] goes? That's right! It goes in the [area] hole!`

I didn't bother adding a cosmetic toggle, but I could probably get that done pretty quickly if desired.

2023-03-29 06:57 UTC, henriquegemignani commented
I'd prefer this via a preset setting, with a different April fools preset and bobs of the date checking.

In particular the date checking might cause tests to fail that day and be unable to release :p

2023-03-30 01:18 UTC, ArcanoxDragon commented
This now requires randovania/open-dread-rando#201 so the negative missiles don't cause a Lua crash

2023-04-03 16:50 UTC, henriquegemignani commented
Since we sadly missed the boat for having this out for the actual April fools, what do you want to do? I'm not opposed to merging all of this (even the april fools hints), but the negative ammo thing will need an adjustment: add a new field to `Ammo` that says if it supports being negative. I know prime 1/2 works, but I don't think it'd work for Cave Story and maybe not other games.

2023-04-03 19:39 UTC, duncathan commented
> I don't think it'd work for Cave Story

would need to test, depending how its set up I might actually already have it configured in such a way it'd work. negative numbers in CS are cursed tho

2023-04-03 20:04 UTC, ArcanoxDragon commented
> Since we sadly missed the boat for having this out for the actual April fools, what do you want to do? I'm not opposed to merging all of this (even the april fools hints), but the negative ammo thing will need an adjustment: add a new field to `Ammo` that says if it supports being negative. I know prime 1/2 works, but I don't think it'd work for Cave Story and maybe not other games.

Ah, that was a pretty big oversight I didn't think of 😅 (this started as a very temporary inside joke, and then myself and those helping me test it decided it was hilarious enough to keep)

I can certainly add a flag that can be specified in the game headers as to whether or not each ammo type supports negative quantities.

2023-04-06 08:30 UTC, henriquegemignani requested changes
Please add the changelog entries!

2023-04-06 08:30 UTC, henriquegemignani commented on randovania/layout/base/ammo_state.py
>                                   f"in range [0, {ammo_item.max_capacity}].")
incorrect range :)

2023-04-06 08:30 UTC, henriquegemignani commented on randovania/layout/base/ammo_state.py
> +            yield from bitpacking.encode_bool(count < 0) # Negative?
this is only needed if `ammo.allows_negative`

2023-04-06 08:30 UTC, henriquegemignani commented on randovania/layout/base/ammo_state.py
> +            if bitpacking.decode_bool(decoder): # Negative?
same, add a `ammo.allows_negative and ` here

2023-04-11 11:38 UTC, henriquegemignani requested changes
This is missing changelog entries!

There should be:
- One for Dread, regarding support for negative expansions.
- One for Dread, regarding the April Fools preset.
- One for Prime 1, regarding the negative expansions.
- One for Prime 2, regarding the negative expansions.

2023-04-11 17:34 UTC, henriquegemignani commented
You do get the reward of changelog conflicts! :)

2023-04-12 06:25 UTC, henriquegemignani approved these changes

2023-04-12 06:33 UTC, merged