Dread: Exclude doors with Sabotoru enemies from door lock rando
randovania/randovania pull request #4235
Opened 2023-03-31 22:51 UTC by Tyranisaur

Closes #4189

2023-03-31 23:00 UTC, XenoWars approved these changes

2023-04-01 05:03 UTC, ThanatosGit requested changes

2023-04-01 05:03 UTC, ThanatosGit commented on CHANGELOG.md
> +- Changed: Exclude doors that get a Sabororu enemy on them from the pool of doors that can have their locks randomized.
`Sabotoru` not `Sabororu`

2023-04-04 07:27 UTC, closed without merging

2023-04-04 07:30 UTC, Tyranisaur commented
Closed this since consensus seems to be that we want patcher support to solve this problem a different way.