Add new "upgrade" items for Metroid Dread
randovania/randovania pull request #4310
Opened 2023-04-23 18:29 UTC by ArcanoxDragon

This PR adds some new items to Dread to expand gameplay options. Corresponds to randovania/open-dread-rando#211.

Currently, the following new items are added:

A "Flash Shift Upgrade" item that increases the number of times you can "chain" a Flash Shift after the first time without needing to wait for Aeion to recharge
A "Speed Boost Upgrade" item that decreases the amount of time it takes for Speed Booster to charge up by 0.25s (for each item collected)

2023-04-23 19:30 UTC, duncathan requested changes

2023-04-23 19:30 UTC, duncathan commented on randovania/games/dread/item_database/item-database.json
> +            "extra": {}
please add a `warning` field to each of these (which is admittedly somewhat poorly named) with the description of each one. for speed upgrade, please mention the minimum possible charge time of 0.25s as well

2023-04-25 06:43 UTC, ArcanoxDragon commented
Will definitely require a new ODR build; randovania/open-dread-rando#214 is necessary for the "ammo" changes.

2023-04-25 16:12 UTC, henriquegemignani commented
Mapping as additional ammo given by Flash Shift means collecting that also gives you 2 upgrades, so if you place 2 Flash Shifts in the pool, the second one you find will also give two additional shifts. Feels like a very unintuitive behavior for those who add extra copies of upgrades, especially because that'd always happen.

I guess you tried it this way to allow the flash upgrades to give you a nerfed flash shift and also out of logic?

If having additional Flash Shifts have consequences, I'd go for merging it with the expansions and just having the first you find give full flash shift and the rest is just +1 shift.

2023-04-25 21:51 UTC, duncathan commented
there were three behaviors they had mentioned they wanted to be possible:
1) collecting main flash shift gives you flash shift and at least 2 chains, while collecting upgrades increases the number of chains without giving you flash shift
2) collecting main flash shift gives you flash shift and 2 chains, while collecting upgrades gives you flash shift and 1 chain
3) instead of having two separate pickups, there's a progressive flash shift pickup that provides 2 chains and flash shift when first collected, and adds 1 chain for subsequent pickups

using ammo was the best way I could come up with to model all of these behaviors, though I don't know if they've all actually been implemented in this pr

2023-04-25 22:23 UTC, ArcanoxDragon commented
All of that is implemented as describe, except for two differences:
- Main Flash Shift gives you _any_ configurable number of chains, including "0" (i.e. you must also collect upgrades to chain)
- Each subsequent Main Flash Shift gives you as many _more_ chains as the first one gave you to begin with. This is due to the way Ammo works in general; PBs are the same way.

2023-04-30 20:58 UTC, henriquegemignani requested changes

2023-04-30 20:58 UTC, henriquegemignani commented on randovania/games/dread/exporter/patch_data_factory.py
> +    if (detail.original_pickup.resource_lock is not None and not detail.original_pickup.respects_lock
Doing `pickup = detail.original_pickup` probably makes this more readable.

2023-05-01 09:54 UTC, henriquegemignani approved these changes

2023-05-01 13:39 UTC, merged