Add "Shuffled (avoid majors)" option to Location Pool settings
randovania/randovania pull request #4354
Opened 2023-05-03 02:58 UTC by ArcanoxDragon

This new option for locations in the Location Pool will exclude the location from containing progression items, but it will also try to avoid placing any item marked as "major" in the location unless there are no other options left.

2023-05-03 15:33 UTC, henriquegemignani commented
Please do try to get coverage of the PR up to the target :)

2023-05-05 19:59 UTC, duncathan requested changes
I don't totally love that we're using two separate lists of nodes, now, but I'm not certain how best to address that

2023-05-05 19:59 UTC, duncathan commented on randovania/generator/generator.py
> +        # for such assignments to happen if there aren't enough remaining locations
probably better to make this a docstring for the function rather than a series of comments

2023-05-05 19:59 UTC, duncathan commented on randovania/layout/base/available_locations.py
> +            minor_only_indices=frozenset(PickupIndex(item) for item in value.get("minor_only_indices", [])),
this is slightly irresponsible. we shouldn't be using `get()` in this context - should instead write a preset migration and guarantee the key will be present

2024-05-26 15:47 UTC, duncathan commented
stale and conflicting. please open a new PR if you'd like to address the review comments!

2024-05-26 15:47 UTC, closed without merging