Dread - Fix room typo
randovania/randovania pull request #4796
Opened 2023-07-15 23:32 UTC by dyceron

Fixes #4745

2023-07-15 23:34 UTC, henriquegemignani approved these changes

2023-07-16 00:08 UTC, duncathan requested changes
I'm pretty sure this requires a migration somewhere

2023-07-16 00:08 UTC, henriquegemignani commented
> I'm pretty sure this requires a migration somewhere

Ah, I forgot to check if it's a starting location.

2023-07-16 00:10 UTC, duncathan commented
what about the dock nodes? won't renaming those break rdvgame imports for seeds with those dock weaknesses randomized without a migration?

2023-07-16 00:11 UTC, henriquegemignani commented
> what about the dock nodes? won't renaming those break rdvgame imports for seeds with those dock weaknesses randomized without a migration?

door lock is a thing, oops. yes it does break things

2023-07-16 00:12 UTC, henriquegemignani commented
Well, that's why the tests failed. There's a test rdvgame with door lock rando that I bet failed.

2023-07-16 01:01 UTC, henriquegemignani requested changes

2023-07-16 01:01 UTC, henriquegemignani commented on test/test_files/log_files/dread/dread_dread_multiworld.rdvgame
> +                "Dairon/East Transport to Ferenia/Elevator to Ferenia - East Transport to Dairon": "Ferenia/East Transport to Dairon",
This pr is **not** allowed to touch any rdvgame.

The tests must pass with the rdvgames being untouched, as they represent all the rdvgames our users have.

2023-08-03 20:43 UTC, ThanatosGit commented
- Reverted the test fixes
- merged main
- wrote a migration (as teleporters are not present currently, only door lock is relevant)

2023-08-11 05:23 UTC, duncathan approved these changes

2023-08-11 05:23 UTC, duncathan commented on test/test_files/patcher_data/dread/crazy_settings.json
> +        "GUI_DIFSELECTOR_LABEL_DESCRIPTOR_EXPERT": "Words Hash ($$$$$)",
every time lmao

2023-08-11 05:46 UTC, merged