Check if base patches is beatable with all pickups
randovania/randovania pull request #4859
Opened 2023-07-21 23:35 UTC by henriquegemignani

Wild first version, not sure how decent it is. Seemed to work?

2023-07-23 10:25 UTC, ThanatosGit requested changes
Let me try to understand and learn the logic here.
After randomisation of elevators, starting area and probably some stuff I forgot about:
1. Resolver is used to check if the game is beatable with every item that will be placed + starting items.
2. If that's true the generator does the job and places the pickups.
3. Validation after generation would still be required because 2. could have placed an item unreachable which was required by 1.

But 1. (so this pr) would remove garbage where e.g. every elevator in a region leads to the same region, such that you could never beat the game.

2023-07-23 10:54 UTC, henriquegemignani commented on randovania/game_description/game_patches.py
> +)
At this point whatever ruff is fine with imports is fine for me.

2023-07-23 11:01 UTC, henriquegemignani commented
> Let me try to understand and learn the logic here. After randomisation of elevators, starting area and probably some stuff I forgot about:

Mostly these two, but a game can shuffle more if they want. Echoes can do translator gates and portals.

>     1. Resolver is used to check if the game is beatable with every item that will be placed + starting items.
> 
>     2. If that's true the generator does the job and places the pickups.
> 
>     3. Validation after generation would still be required because 2. could have placed an item unreachable which was required by 1.
> 
> 
> But 1. (so this pr) would remove garbage where e.g. every elevator in a region leads to the same region, such that you could never beat the game.

Correct. 

I also wanted to catch starting at bad locations, but I don't think this does it. Some sort of baby generator where it checks how much you can reach with no pickups plus additional starting pickups would be needed.

2023-07-23 12:01 UTC, ThanatosGit commented on randovania/game_description/game_patches.py
> +)
Then go for it :p

2023-07-23 12:01 UTC, ThanatosGit approved these changes

2023-07-27 11:50 UTC, henriquegemignani commented
Will merge after 6.1

2023-08-03 20:46 UTC, ThanatosGit commented
Oh, the merge failed.

2023-08-03 21:56 UTC, merged