AM2R: Add Patcher
randovania/randovania pull request #4881
Opened 2023-07-24 17:24 UTC by Miepee

Attempt number 2!
Tested this on Linux, Jeff has been running 0.0.1 for a bit on Windows, I have absolutely no idea how this behaves on Mac.

2023-07-24 18:04 UTC, henriquegemignani requested changes
Add a test that mocks `patch_game` and asserts it's called.

2023-07-24 19:23 UTC, henriquegemignani approved these changes

2023-07-24 22:03 UTC, Miepee commented
Currently blocked by the fact that the dotnet runtime from am2r_yams keeps being loaded, and causing the linux runner to crash.

2023-08-08 19:32 UTC, henriquegemignani approved these changes

2023-08-08 19:51 UTC, merged