Add Phazon Suit Hint location to Hints page
randovania/randovania pull request #4933
Opened 2023-07-29 22:34 UTC by dyceron

Fixes #4926 

![image](https://github.com/randovania/randovania/assets/38679103/9e2e8859-430d-4244-b909-df5653b9b575)

2023-07-29 22:37 UTC, Uncle-Reggie approved these changes
Hey look what I learned how to do. 👍

2023-07-29 22:38 UTC, henriquegemignani requested changes

2023-07-29 22:38 UTC, henriquegemignani commented on CHANGELOG.md
> +### Metroid Prime
This entry is in the middle of Dread section

2023-07-29 22:40 UTC, Uncle-Reggie commented
Goddamnit I messed up the first one I learned to do

2023-07-30 00:11 UTC, henriquegemignani approved these changes

2023-07-30 00:20 UTC, merged