### Echoes: Logic Updates and Video Uploads
randovania/randovania pull request #4967
Opened 2023-08-03 11:40 UTC by CMos75

#### logic database

- Added: 306 videos to the logic database. see the [Video Directory] (https://randovania.github.io/Metroid%20Prime%202%20Echoes/) for the full collection

##### Temple Grounds:

- Added:  NSJ Extended Dash (Expert) to cross Grand Windchamber through the middle platform.

##### Agon Wastes:

- Added: NSJ Extended Dash (Advanced) to reach Temple Access Door in Mining Station A.

##### Sky Temple Ground:

- Removed: Phazon Grounds NSJ, No SA -> Invisibil Objects (Hypermode) or Movement (Expert) and Dark Visor. Doesn't exist.

##### Sanctuary Fortress:

- Added: Extended Dash (Expert) to reach the Scan Post in Watch Station Access from Main Gyro Chamber Door.
- Added: Extended Dash (Expert) to reach Main Gyro Chamber Door in Watch Station Access from the Scan Post Side.

2023-08-04 09:45 UTC, henriquegemignani requested changes

2023-08-04 09:45 UTC, henriquegemignani commented on randovania/games/prime2/json_data/Temple Grounds.txt
> +                      # https://www.youtube.com/watch?t=17&v=JRT1SEeWKv8&feature=youtu.be
This causes issues with the code that generates the video directory.

2023-08-14 11:14 UTC, henriquegemignani commented
@dyceron can you take a look, particularly the difficulty changes

2023-08-15 21:09 UTC, dyceron requested changes
I stopped pointing out each case, but saying "Use Double Bomb Jump" as a comment is weird and should just say "Double Bomb Jump" since it still gets the point across and more correct.

2023-08-16 14:34 UTC, dyceron requested changes
Also fix the changelog conflicts

2023-08-16 14:34 UTC, dyceron commented on randovania/games/prime2/json_data/Temple Grounds.txt
> +                  # Use Power Bombs to exit Boost Ball Spinners
Add this comment to the yellow Seeker lock path as well

2023-08-16 15:57 UTC, merged