Prime1: Fixed PPC NSJ Logic from Bottom
randovania/randovania pull request #4970
Opened 2023-08-04 00:36 UTC by Samuel6710

2023-08-04 03:21 UTC, JeffGainsNGames requested changes
Update changelog

2023-08-05 16:59 UTC, toasterparty requested changes

2023-08-05 16:59 UTC, toasterparty commented on CHANGELOG.md
> +- Changed: PPC Climb NSJ Fix
```
Fixed: NSJ Phazon Processing Center having too few requirements
```

2023-08-07 00:48 UTC, toasterparty approved these changes

2023-08-07 00:58 UTC, merged