Prime1: Logic Update
randovania/randovania pull request #5159
Opened 2023-08-27 03:37 UTC by Samuel6710

##### Chozo Ruins

- Added: Reverse Flaahgra in Sun Tower is now logical
- Added: Furnace E Tank Wall Boost Escape
- Added: Transport Access North Wallboost to Hive Totem from Elevator
- Added: Trigger Ghosts from Sun Tower Access without Bombs or Spider

##### Phazon Mines

- Added: Fungal Hall A now has Energy and Combat Logic
- Added: Fungal Hall A SJ Scan Dash Grapple Skip
- Added: Fungal Hall Access NSJ Bombless Escape to Fungal Hall A

##### Phendrana Drifts

- Changed: Phendrana Canyon Pickup NSJ Bombless Triple Boost Adjustments
- Added: Hunter Cave Bunny Hop to reach Hunter Cave Access from Lower Edge Tunnel
- Added: Hunter Cave Slope Jump to reach Chamber Access from Lake Tunnel

##### Tallon Overworld

- Added: Root Cave Climb NSJ Boost Strat

2023-08-27 17:20 UTC, toasterparty commented
@henriquegemignani Is there going to be a problem with sunchamber + suntower PoNR like we had years ago?

2023-08-28 08:40 UTC, henriquegemignani commented
> @henriquegemignani Is there going to be a problem with sunchamber + suntower PoNR like we had years ago?

Best to investigate and see what happens. Generate a bunch before and after and compare results.

2023-08-28 20:03 UTC, toasterparty requested changes

2023-08-28 20:03 UTC, toasterparty commented on randovania/games/prime1/json_data/Phazon Mines.txt
> +          Any of the following:
Uncharged plasma feels pretty powerful here. At the end of the day, writing logic like this just plain sucks, so don't feel like you have to for every room.

Also remember that you are picking health values that come before the normal 1.5x scaling randovania does by default.

2023-08-28 20:03 UTC, toasterparty commented on randovania/games/prime1/json_data/Chozo Ruins.txt
> +              Instant Unmorph Jump (Hypermode)
my boi you need sj

2023-08-28 20:04 UTC, Samuel6710 commented on randovania/games/prime1/json_data/Phendrana Drifts.txt
> +      # https://youtu.be/oPvUjPIBQQo?t=27
I tried it out myself. The collision of the ledge is misleading, the standable part of the slope extends a lot more than it looks like it does.

2023-08-28 20:06 UTC, Samuel6710 commented
I'll be able to get these changes in later today.

2023-08-28 20:08 UTC, toasterparty commented on randovania/games/prime1/json_data/Phendrana Drifts.txt
> +      # https://youtu.be/oPvUjPIBQQo?t=27
all good

2023-08-28 22:47 UTC, toasterparty commented on randovania/games/prime1/json_data/Phazon Mines.txt
> +          Any of the following:
You increased the numbers but my concern was that they were too high. How did you test these numbers? They should represent the best possible scenario, not the least.

2023-08-28 22:48 UTC, toasterparty requested changes

2023-08-28 22:48 UTC, toasterparty commented on randovania/games/prime1/json_data/Tallon Overworld.txt
> +      Trivial
Trivial? 🙃

2023-08-28 22:49 UTC, Samuel6710 commented on randovania/games/prime1/json_data/Tallon Overworld.txt
> +      Trivial
??

2023-08-28 22:50 UTC, Samuel6710 commented on randovania/games/prime1/json_data/Tallon Overworld.txt
> +      Trivial
Oh I see what I did wrong

2023-08-29 22:42 UTC, Samuel6710 commented
@toasterparty Let me know what you think :)

2023-08-29 23:13 UTC, toasterparty approved these changes

2023-09-01 22:33 UTC, merged