Feat/dread add warning about custom text
randovania/randovania pull request #5352
Opened 2023-09-25 18:21 UTC by Batro

2023-09-25 18:23 UTC, Batro commented
Adresses the confusion reported in #5248

2023-09-26 23:48 UTC, dyceron requested changes

2023-09-26 23:48 UTC, dyceron commented on randovania/games/dread/game_data.py
> +        ),
```suggestion
        (
            "Why are items, hints, and the seed hash not displaying properly in my game?",
            "Currently, English is the only supported language.\n\n"
            "You must set your language to English to see all the text the randomizer changes.",
        ),
```

2023-09-27 17:02 UTC, dyceron requested changes

2023-09-27 17:02 UTC, dyceron commented on CHANGELOG.md
> +- Added: Warning in the FAQ section about custom text only fully displayed when running the game in English.
```suggestion
- Added: Warning in the FAQ about custom text not displaying if the game is played in languages other than English.
```

2023-09-30 13:32 UTC, ThanatosGit commented
@dyceron Can you approve the changes? This is one of the few things, which touches something in a stable game, I would agree to merge right before a new version.

2023-09-30 13:54 UTC, dyceron approved these changes

2023-09-30 14:12 UTC, merged