Resolver/fix damage logic
randovania/randovania pull request #5375
Opened 2023-09-29 15:36 UTC by Tyranisaur

2023-09-29 16:56 UTC, Miepee commented on CHANGELOG.md
> +- Fixed: Bug where damage constraints in chains were not understood correctly.
You should also add a changelog entry that prime doesnt have multiplicative suit reductions anymore.

2023-10-01 15:45 UTC, henriquegemignani requested changes

2023-10-01 15:45 UTC, henriquegemignani commented on randovania/game_description/game_description.py
> +                    elif individual.is_damage and individual.satisfied(resources, current_energy, database):
Do you think you could make a test case for this function? It'll be a bit tricker as this function doesn't have tests yet though :(

2023-10-02 20:43 UTC, henriquegemignani approved these changes

2023-10-03 06:30 UTC, ThanatosGit commented
The usual "new version = changelog conflict" thing.

2023-10-03 16:43 UTC, Tyranisaur commented
> The usual "new version = changelog conflict" thing.

I also moved the changelog entries to the correct version :)

2023-10-03 16:45 UTC, ThanatosGit commented on CHANGELOG.md
> +
unintentional new line in 6.3.0?

2023-10-03 17:27 UTC, merged