Workaround for images not working in built-in changelog widget
randovania/randovania pull request #5416
Opened 2023-10-05 08:51 UTC by Wolfmyths

This PR is for issue #4621

### Additions:
+ Created a function to find image tags in the markdown of changelogs and then create new labels where the images should be in the markdown.
    - This function only runs if there are image tags in a changelog.
    - In the case of an http error from getting the image, the error will display where the image would be in the GUI
+ Created a function to reuse the code for setters in DelayedTextLabels

### Notes:
+ A DelayedTextLabel is created for every block of markdown before and after an image, images are DelayedTextLabels too.
    - This is to make patch notes look as identical as possible to the original release markdown
+ Uses the requests module to obtain images
+ Imported regex to easily parse the markdown

### How I tested it:
+ Created and ran pytests for the new function in `test_changelog_widget.py`
+ Checked changelog versions 0.9.0 and 0.10.0 and they display the same as if they were on github

### Concerns:
+ Unsure what library you guys want to use for getting images (PySide6's networking, requests, urllib)
+ Exception handling for getting images from the internet
+ Code readability
+ All images are loaded during changelog's `__init__` which could cost performance in the future
+ Using requests module freezes the program especially if the user has a slow connection
+ Changelog widget does not resize automatically when there are images that are too big to show in the widget

![Capture12](https://github.com/randovania/randovania/assets/118236986/c3bd60a0-28f3-4e1d-aa17-38dbcc4a8fb8)
![Capture11](https://github.com/randovania/randovania/assets/118236986/687bd688-1b71-48a3-a5c9-e22946bba447)

2023-10-16 08:58 UTC, Miepee commented
Sorry for the late response. Don't have the time to review yet, but can you please make sure that the Executable tests don't fail?

2023-10-16 08:59 UTC, Miepee commented on randovania/gui/widgets/changelog_widget.py
> +    def image_parse(self, version_text: str) -> list[DelayedTextLabel] | None:
You also probably want to fix this mypy error

2023-10-20 11:03 UTC, henriquegemignani requested changes
The test failures is because `requests` is only installed for the server. Client code we use `aiohttp` to have non-blocking requests.
Which is another issue in this PR: it downloads the image synchronously during widget creation, which can be quite slow!

2023-10-20 11:07 UTC, henriquegemignani commented
Which I did not see you mentioned in the PR description, ooops!

The rest seems fine for me. But adding some placeholder text while the image downloads seems best for me. The placeholder would also work to indicate if the download fails.

2023-10-21 07:57 UTC, Wolfmyths commented
Sorry for the late response, I was able to implement aiohttp and got it to work.

The only issue I have right now that I am stumped on is pytest. I'm probably missing something simple as I'm fairly new to async and pytest.

When test_changelog.py is tested, errors come up about the async function `setup_labels()` saying this:
```
asyncio:base_events.py:1771 Task was destroyed but it is pending!
```
this error is the catalyst to an assert error because the task was never finished. Other test modules also complain about the async function.

> The rest seems fine for me. But adding some placeholder text while the image downloads seems best for me. The placeholder would also work to indicate if the download fails.

I'll add that when I can

2024-01-31 20:45 UTC, ThanatosGit commented
Do you still work on this or need help?

2024-02-01 05:15 UTC, Wolfmyths commented
> Do you still work on this or need help?

I'll take a look tomorrow and see if I can fix it

2024-02-01 15:12 UTC, Wolfmyths commented
Yeah I still need help, my knowledge of pytest is very basic especially with async stuff.

My code works when I run it, for some reason pytest is giving me a hard time.

The test is setup to create the changelog widget like normal, and it will wait for the signal that is emitted when the changelog is done fetching and placing the data.

However even though this waitSignal function is passed, an assertion error is thrown on the first assert `0 == 4`

I am at a loss for what the problem is

2024-02-01 17:05 UTC, ThanatosGit commented
Uh, looks kinda weird to me, too.
I'm not 100 % sure how `waitSignal` works.
`If your program has long running computations running in other threads or processes, you can use qtbot.waitSignal to block a test until a signal is emitted`
So, maybe it is blocking the qt event loop? That would make sense why the test code doesn't work. Also I think the within the `with` block you would write code to call something which will eventuall emit the signal from `waitSignal`.

I quickly hacked something together and pushed it: Basic idea is to mock the `startFetchingData` but assert that it is called and then call the `setup_lables` manually (and get rid of the leaked not awaited function call in `test_main_window`.

2024-02-01 19:29 UTC, ThanatosGit requested changes
Needs an entry in the `CHANGELOG.md` and then we are good to go, I guess.

2024-02-02 03:55 UTC, ThanatosGit requested changes
Oops, I'm very sorry, I was so heavily focused on the logic that I didn't notice the naming.
I must admit that's because Qt is using camelCase and therefore it is heavily mixed in the gui related parts anyways. 
But at least we want to be consistent with our own variables, fields etc.

2024-02-02 03:55 UTC, ThanatosGit commented on randovania/gui/widgets/changelog_widget.py
> +    doneFetchingData = QtCore.Signal()
snake _case

2024-02-02 03:55 UTC, ThanatosGit commented on randovania/gui/widgets/changelog_widget.py
> +    startFetchingData = QtCore.Signal()
snake_case

2024-02-02 03:55 UTC, ThanatosGit commented on randovania/gui/widgets/changelog_widget.py
> +    async def setup_lables(self) -> None:
It's `labels` and not `lables`, isn't it?

2024-02-02 03:55 UTC, ThanatosGit commented on test/gui/test_main_window.py
> +    monkeypatch.setattr(ChangeLogWidget, "setup_lables", MagicMock())
Same function, same typo, just that this one won't get catched with (at least my) automatic refactoring.

2024-02-02 03:55 UTC, ThanatosGit commented on test/gui/widgets/test_changelog_widget.py
> +    mocked_fetch = mocker.patch("randovania.gui.widgets.changelog_widget.ChangeLogWidget.startFetchingData")
snake_case for thr patched field.
Guess this also won't be catched by refactoring.

2024-02-02 03:55 UTC, ThanatosGit commented on test/gui/widgets/test_changelog_widget.py
> +    qLabel0 = cast(DelayedTextLabel, qFrame0.findChild(DelayedTextLabel))
snake_case for all the `qBlaX` variables.
`qScroll0` was already there before but would be nice to fix that

2024-02-02 15:25 UTC, ThanatosGit approved these changes

2024-02-08 20:04 UTC, ThanatosGit commented
@henriquegemignani You wanna re-review it or should I just dismiss?

2024-02-08 20:17 UTC, henriquegemignani commented on randovania/gui/widgets/changelog_widget.py
> +        for version_name, version_text in self.all_change_logs.items():
Downloading every single image is not great, but we can change that later

2024-02-08 20:17 UTC, henriquegemignani approved these changes

2024-02-09 09:27 UTC, Miepee commented
@Wolfmyths sorry, but can you rebase and put the changelog entry into 7.3.1?

2024-02-09 17:17 UTC, ThanatosGit commented
Just did it quickly. It's faster for me to click the "Update branch" button and quickly change the changelog via the github online editor than to ask, watch this pr later again + write this message here 😛

2024-02-09 17:32 UTC, merged