Mark PB limitation as unsupported feature.
randovania/randovania pull request #5424
Opened 2023-10-07 11:36 UTC by henriquegemignani

![image](https://github.com/randovania/randovania/assets/884928/5b15d479-e85c-4c6d-be6d-95fc7fc1d7e3)

2023-10-07 13:12 UTC, Tyranisaur requested changes

2023-10-07 13:35 UTC, henriquegemignani commented on CHANGELOG.md
> +- Removed: The "Power Bomb Limitations" has been disabled due to issues. This will be re-added in the future.
yeah

2023-10-07 13:37 UTC, Tyranisaur approved these changes

2023-10-08 16:05 UTC, ThanatosGit approved these changes

2023-10-08 16:22 UTC, merged