Fix exporting Echoes with Memo popup enabled, hidden collection text and cross-game multiworld
randovania/randovania pull request #5678
Opened 2023-12-01 18:49 UTC by henriquegemignani

2023-12-07 07:31 UTC, ThanatosGit requested changes
Looks fine to me so far.
I'm just concerned about the failing test. There are a lot of additional (test) files which create a `PickupEntry` but using just an `int` as second parameter. Second parameter should be a `PickupModel` and now a test fails because you actually access the model now.
Isn't really a problem of this PR but kinda because now the tests are failing (though they were already wrong before).

2024-02-14 19:16 UTC, henriquegemignani commented
Fixed tests

2024-02-14 23:13 UTC, Miepee commented
changelog conflicts

2024-02-16 06:56 UTC, ThanatosGit approved these changes

2024-02-16 09:22 UTC, merged