MSR - Add support for Reserve Tanks
randovania/randovania pull request #5687
Opened 2023-12-05 02:05 UTC by dyceron

Adds support for the amiibo Reserve Tanks as shuffleable items
![image](https://github.com/randovania/randovania/assets/38679103/5ec76a76-cc9d-4e83-ab94-2eeb44f7f4cd)
![image](https://github.com/randovania/randovania/assets/38679103/cbee9687-0c1c-4f95-b346-46e059044858)
![image](https://github.com/randovania/randovania/assets/38679103/e48122e7-3d8b-4936-99ca-37481bbc42fe)

2023-12-07 15:10 UTC, ThanatosGit requested changes

2023-12-07 15:10 UTC, ThanatosGit commented on randovania/games/samus_returns/layout/preset_describer.py
Can you add / modify the tests for this file to cover the added lines? We already have a file for it, so it's hopefully a low hanging fruit: https://github.com/randovania/randovania/blob/main/test/games/samus_returns/layout/test_msr_describer.py

2023-12-08 02:26 UTC, dyceron commented
I changed where and how the preset changes are handled. It is now also covered by the current tests. 
![image](https://github.com/randovania/randovania/assets/38679103/71c5b123-ade2-4e41-bb58-f6b8dadfb66b)

2023-12-08 04:58 UTC, ThanatosGit approved these changes

2023-12-08 05:07 UTC, merged