MSR - Add hint tab to generated game window
randovania/randovania pull request #5726
Opened 2023-12-15 00:30 UTC by dyceron

Adds the Hint Tab to the generated game window. I don't know why there's so much padding for each hint

![image](https://github.com/randovania/randovania/assets/38679103/cf5ce25a-bb0c-4547-9307-615d1bd5ac54)

2023-12-15 07:23 UTC, ThanatosGit commented
> I don't know why there's so much padding for each hint

Uh...this is using the text how it get's exported. Atm the patcher has the assumption that every hint ends with newline character `\n`. Per message box it gathers three lines by splitting at `\n`.
a) We don't use multi hints per station. Could be removed or being kept for future 
b) Either we change this in the patcher to not force every line with `\n` or change it before showing in the UI here.

2023-12-15 10:57 UTC, dyceron commented
> Uh...this is using the text how it get's exported. Atm the patcher has the assumption that every hint ends with newline character `\n`. Per message box it gathers three lines by splitting at `\n`.
> a) We don't use multi hints per station. Could be removed or being kept for future 
> b) Either we change this in the patcher to not force every line with `\n` or change it before showing in the UI here.
> 

Ah that makes sense. I guess we could leave it for now in case we change hints later.

2023-12-15 11:09 UTC, ThanatosGit requested changes

2023-12-15 11:09 UTC, ThanatosGit commented on randovania/games/samus_returns/gui/hint_details_tab.py
> +            hint_text = exporter.create_message_for_hint(hint, all_patches, players, False)
If you don't want to change the patcher now, use `.strip()` at the end of this line.
It should remove the new line and fix the padding.

2023-12-15 11:09 UTC, ThanatosGit commented on randovania/games/samus_returns/gui/hint_details_tab.py
> +    def update_content(
Don't know if we have any tests but also I don't mind it for such a simple non crucial thing.
But: Minimum should be to add the return type here for mypy.

2023-12-16 11:41 UTC, dyceron commented
I can't seem to find the test file for this. Do I even need to test for this?

2023-12-16 14:19 UTC, ThanatosGit commented
> I can't seem to find the test file for this. Do I even need to test for this?

That's exactly what I said :p `Don't know if we have any tests but also I don't mind it for such a simple non crucial thing.`

2023-12-16 14:19 UTC, ThanatosGit approved these changes

2023-12-16 14:19 UTC, dyceron commented
> > I can't seem to find the test file for this. Do I even need to test for this?
> 
> That's exactly what I said :p `Don't know if we have any tests but also I don't mind it for such a simple non crucial thing.`

Fair enough

2023-12-16 14:26 UTC, merged