AM2R MW: fix progressives with random starting items
randovania/randovania pull request #5859
Opened 2024-01-16 19:44 UTC by Miepee

When geting random starting items, the game gives you the resource directly (i.e. `Hi-Jump`). Thus mixing between the normal resource and the progressive, which we need to account for.

2024-01-16 20:02 UTC, henriquegemignani requested changes

2024-01-16 20:02 UTC, henriquegemignani commented on randovania/game_connection/connector/am2r_remote_connector.py
> +            while True:
`for index in itertools.count():`

2024-01-16 20:06 UTC, henriquegemignani commented
can you be more exhaustive with the testing? Both test cases end up with both Hi-Jump and Space Jump, for example.

tbh I don't quite follow why this code works

2024-01-16 20:46 UTC, Miepee commented
I added a comment to hopefully explain it better.

2024-01-16 23:58 UTC, duncathan commented
I feel like you should probably just give the correct resource for the starting items? this seems awfully messy

tbh I don't understand why you distinguish between progressive and non-progressive items in the inventory to begin with

2024-01-17 09:56 UTC, Miepee commented
> It's kind of nonsense to keep track of the names of the Pickups you've collected

This made me realize on how to fix it. I can just overwrite the name that gets added to the inventory, so i'll just do that there for the progressive stuff, and close this PR to not make this section more unreadable.

2024-01-17 09:56 UTC, closed without merging