MP2: Training Chamber Reverse Air Underwater
randovania/randovania pull request #6137
Opened 2024-03-11 05:39 UTC by SchwartzGandhi

Added an NSJ method for the Reverse Air Underwater in training chamber and adjusted logic accordingly (video provided)

2024-03-11 16:09 UTC, Samuel6710 requested changes

2024-03-11 16:09 UTC, Samuel6710 commented on randovania/games/prime2/logic_database/Torvus Bog.txt
> +              # https://www.youtube.com/watch?v=LgeZpkGDQjw
Truncate: https://youtu.be/LgeZpkGDQjw

2024-03-11 20:21 UTC, Samuel6710 approved these changes

2024-03-16 16:14 UTC, Miepee commented
@SchwartzGandhi changelog conflicts

2024-03-16 16:46 UTC, merged