Prime: Implement refills to the item pool.
randovania/randovania pull request #6158
Opened 2024-03-13 22:35 UTC by MrMiguel211

![image](https://github.com/randovania/randovania/assets/60329473/ddb6cc5e-85ce-4f20-8b4f-ba86c05a160d)
![GM8E01_2024-03-13_15-35-09](https://github.com/randovania/randovania/assets/60329473/f4a84f57-d775-4967-8d55-0326a4bd6563)

2024-03-13 22:39 UTC, Miepee commented
Needs fixed tests, I'll do those later

2024-03-16 13:56 UTC, Miepee commented
New screenshots after the long name rename:
GUI:
![grafik](https://github.com/randovania/randovania/assets/38186597/86214999-a0ee-4a92-ac84-6462528606dd)

In-Game:
![grafik](https://github.com/randovania/randovania/assets/38186597/08ef88df-edcf-4749-ad7d-3f54facc3a16)
![grafik](https://github.com/randovania/randovania/assets/38186597/b8a9774d-10a5-4104-9bd9-1e9ce7f17522)
![grafik](https://github.com/randovania/randovania/assets/38186597/60fe9075-39ca-43a2-8abe-ef684601e307)

2024-04-11 18:37 UTC, toasterparty requested changes

2024-04-11 18:37 UTC, toasterparty commented on randovania/games/prime1/pickup_database/pickup-database.json
> +        },
`Health` -> `Energy` for player-facing text

2024-04-11 18:37 UTC, toasterparty commented on randovania/games/prime1/pickup_database/pickup-database.json
> +            "description": "Refills your Power Bombs by a set amount."
Replace `a set amount`  by how much they actually refill

2024-04-11 18:38 UTC, toasterparty commented
Did this really just work in MultiWorld without having to finagle anything?

2024-04-11 18:39 UTC, Miepee commented
MW wasnt tested yet. Wanted to do this in beta builds because its easier to test.

2024-04-11 18:59 UTC, henriquegemignani commented
> Did this really just work in MultiWorld without having to finagle anything?

Does giving the health work by incrementing the amount/capacity of an given item or is there any extra functionality?

2024-04-11 19:00 UTC, henriquegemignani commented
Oh there's also missile and pb refills. I'm pretty confident these will need special handling to receive, otherwise they'll also give capacity.

2024-04-11 22:39 UTC, toasterparty approved these changes
I'm approving even though I have doubts about this actually working first try. Please test as soon as this hits the server and don't merge unless you're going to be able to test that day, thanks.

2024-04-11 22:49 UTC, henriquegemignani commented
> I'm approving even though I have doubts about this actually working first try. Please test as soon as this hits the server and don't merge unless you're going to be able to test that day, thanks.

Swap my "pretty confident" to 100% sure. Receiving a missile or pb refill remotely will give you capacity. Dunno about energy refill though.

2024-04-11 23:46 UTC, toasterparty requested changes
un-approving, please demonstrate that this is working on a bench multiworld

2024-05-16 20:34 UTC, toasterparty commented
tests? conflict.

2024-05-16 20:35 UTC, Miepee commented
tests are normal, we're a bit flakey
conlfict is expected. I couldnt figure out yet how to make this work with MW. 
In the meantime, I figured out tho how to mark presets with refill items as incompatible for MW, would that be an acceptible workaround to get this merged?

2024-05-16 20:40 UTC, Miepee commented
I just remembered this discusssion:
![grafik](https://github.com/randovania/randovania/assets/38186597/b0595cfc-5187-4eb3-b743-50dc5628e62f)


I could try pursuing this further, but this wont happen before next month. So up to you if this should get longer in limbo, or if we just exclude them from MW. I'm fine with either.

2024-06-26 10:41 UTC, ThanatosGit commented
What's the status here?
If it isn't mergable and nobody is working on that, I prefer to change it to a Draft.

2024-06-26 10:42 UTC, Miepee commented
Status is "needs MW functionality".
Draft sounds like a good idea.

2024-07-10 19:50 UTC, Miepee commented
@toasterparty this should be rebased, and Jeff told in prime-dev that it worked in MW now.
Hopefully we can get this merged soon :)

2024-07-21 22:28 UTC, toasterparty requested changes
- Fix merge conflict
- Add refill pickups to one of the test rdvgame files

2024-07-22 01:39 UTC, Miepee commented
Fixed/Added both.

2024-07-22 02:19 UTC, toasterparty approved these changes

2024-07-22 07:53 UTC, merged