Ridley Combat Logic Overhaul
randovania/randovania pull request #6230
Opened 2024-03-24 23:13 UTC by Samuel6710

2024-03-24 23:17 UTC, JeffGainsNGames commented
+120k diff

2024-03-24 23:23 UTC, Samuel6710 commented
May have added py-randomprime to the folder

2024-03-25 00:14 UTC, JeffGainsNGames requested changes

2024-03-25 00:14 UTC, JeffGainsNGames commented on randovania/games/prime1/logic_database/Tallon Overworld.txt
> +          Have all Artifacts
You are missing a change in the header file to define this new template. I imagine you lost the change somewhere when recreating the branch.

2024-03-27 23:25 UTC, Miepee requested changes
The health logic for ridley seems totally scuffed, would even say that its worse. It basically causes "you have charge beam, now go fight ridley hitless, gl" after combat beginner.

Try seperating this into:
```
ALL
 # Phase 1 Item requiements
 # Phase 2 Item requirements
 # Phase 3 Item requirements
 # Total health requirements
 ```

2024-03-28 22:04 UTC, Samuel6710 commented
I'm going to redo these changes from the ground up since Miepee makes some good points about why it's flawed and it could cause a lot of problems.

2024-03-28 22:04 UTC, closed without merging