Add credits elements function
randovania/randovania pull request #6249
Opened 2024-03-28 15:12 UTC by Miepee

Adds a function that gives some building blocks for someone to make their own credits spoiler function. Originally written because Fusion needed something like that.

Unsure if and what the best way to test this is. The other spoiler functions don't have any tests, and this will later get indirectly tested by Fusion's PDF.

Example output:
![grafik](https://github.com/randovania/randovania/assets/38186597/d66f826a-8751-44f2-a14a-abffc3d0000b)

2024-04-07 18:28 UTC, ThanatosGit commented
I'm not a big fan of adding dead code for "maybe future"™

2024-04-07 18:29 UTC, Miepee commented
Talked with this with darkszero already. Plan to add tests soon:tm:. Fusion is guaranteed (technically does already) to use this in its PDF.

2024-04-07 18:48 UTC, ThanatosGit commented
I don't know...still not a big fan of it because it's dead code now in this PR and could be added when it's needed + it's like the problem with copy & paste code reversed: Adding a generic function which no one uses except one game.

I haven't looked into it but isn't it possible to refactor something like the `generic_credits` thing to use this? Then it would be used by....uh 3?...games and game specific parts could also access this helper function here directly.

2024-04-07 18:49 UTC, ThanatosGit requested changes

2024-04-07 18:49 UTC, ThanatosGit commented on randovania/exporter/hints/credits_spoiler.py
> +    def sort_pickup(p: str) -> (float, str):
Syntax error

2024-04-07 18:50 UTC, Miepee commented
IIRC there was something that was holding me back, but can't remember anymore.

2024-05-26 15:58 UTC, duncathan commented
I think this needs to be a proper refactor instead of implemented like this

2024-05-26 15:58 UTC, closed without merging