MSR: a3 MC
randovania/randovania pull request #6291
Opened 2024-04-03 01:36 UTC by Miepee

2024-04-03 02:45 UTC, dyceron requested changes

2024-04-03 02:45 UTC, dyceron commented on randovania/games/samus_returns/logic_database/Area 3 - Metroid Caverns.txt
> +                  # Freeze and clip into Ramulken: https://youtu.be/RJkXLo_UohI - TODO: find more ways
Freeze Ramulken in corner and Melee Clip right

2024-04-03 02:45 UTC, dyceron commented on randovania/games/samus_returns/logic_database/Area 3 - Metroid Caverns.txt
> +              Power Bomb and Lay Power Bomb
2 PBs

2024-04-04 14:11 UTC, Miepee commented on randovania/games/samus_returns/logic_database/Area 3 - Metroid Caverns.txt
> +              Power Bomb and Lay Power Bomb
using 3 just to be safe

2024-04-04 15:34 UTC, merged