Add field in rdvgames that overrides Patch Data Factory output
randovania/randovania pull request #6294
Opened 2024-04-03 04:33 UTC by MayberryZoom

- Game specific PDFs now override `create_game_specific_data`, which is then invoked by the common PDF
- Adds a `custom_patcher_data` field to GamePatches
- Adds a package requirement for `json-delta`

Conflicts with #6250. Unsure if PDF changes conflict with others.

2024-04-04 14:45 UTC, Miepee commented on randovania/exporter/patch_data_factory.py
> +        return patch(game_data, self.patches.custom_patcher_data, False)
Can you write a test please, that tests that this behaves as it should with custom extra data?

2024-04-04 20:08 UTC, henriquegemignani requested changes
You're missing including the value in `serialize_single` too.

And I agree that some test should use this. It can easily be changing, or adding, a new rdvgame to the test suite. Could be even your plando :P

2024-04-04 20:08 UTC, henriquegemignani commented on randovania/games/prime2/exporter/patch_data_factory.py
> +    return EchoesPatchDataFactory(description, players_config, cosmetic_patches).create_game_specific_data()
should be create_data

2024-04-04 20:08 UTC, henriquegemignani commented on randovania/games/prime2/exporter/patch_data_factory.py
> +    return EchoesPatchDataFactory(description, players_config, cosmetic_patches).create_game_specific_data()
actually delete this function 🤣

2024-04-04 20:08 UTC, henriquegemignani commented on randovania/exporter/patch_data_factory.py
> +from json_delta import patch
I prefer just `import json_delta` and then you use `json_delta.patch`

2024-04-04 20:12 UTC, MayberryZoom commented on randovania/games/prime2/exporter/patch_data_factory.py
> +    return EchoesPatchDataFactory(description, players_config, cosmetic_patches).create_game_specific_data()
Delete `generate_patcher_data`?

2024-04-04 20:13 UTC, henriquegemignani commented on randovania/games/prime2/exporter/patch_data_factory.py
> +    return EchoesPatchDataFactory(description, players_config, cosmetic_patches).create_game_specific_data()
yeah, it's an unused function

2024-04-04 20:17 UTC, MayberryZoom commented
> You're missing including the value in `serialize_single` too.

Wouldn't that make it write it to the rdvgame? I thought the idea was that it had to be manually added.

> And I agree that some test should use this. It can easily be changing, or adding, a new rdvgame to the test suite. Could be even your plando :P

Should there be one for each game, or will just one do?

2024-04-05 10:53 UTC, henriquegemignani approved these changes
Not sure if this need a changelog entry

2024-04-05 11:01 UTC, merged