Cave Story: Revise Sand Zone
randovania/randovania pull request #6380
Opened 2024-04-14 14:25 UTC by Miepee

Health numbers for convenience:

Curly:
14 -> 21
9 -> 14

Omega:
19 -> 29
10 -> 15

Toroko+
22 -> 33
15 -> 23
9 -> 14

2024-04-15 21:20 UTC, duncathan requested changes

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +                  # Break Blocks with Missiles
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +              # Break Blocks with Bubbler
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +                  # Break Blocks with Missiles
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +              # Break Blocks with Bubbler
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +                  # Break Blocks with Missiles
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +                      # Kill with Missiles
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +                      # Kill with Super Missiles
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +          # Break Blocks with Bubbler
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +              # Break Blocks with Missiles
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +              # Break Blocks with Missiles
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +          # Break Blocks with Bubbler
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +              # Break the Blocks
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +              # Break Blocks with Bubbler
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +                  # Break Blocks with Missiles
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +          # Break Blocks with Bubbler
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +              # Break Blocks with Missiles
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +              # Break Blocks with Bubbler
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +                  # Break Blocks with Missiles
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +          # Break Blocks with Bubbler
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +              # Break Blocks with Missiles
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +          # Break Blocks with Bubbler
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +              # Break Blocks with Missiles
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +              # Kill with Super Missiles
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +              # Kill with Super Missiles
.

2024-04-15 21:20 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +              # Kill with Missiles
.

2024-04-17 13:47 UTC, Miepee commented
Removed all those comments except for the Omega fight due to the omega requirements being a bit big.

2024-04-17 15:16 UTC, duncathan requested changes

2024-04-17 15:16 UTC, duncathan commented on randovania/games/cave_story/logic_database/Sand Zone.txt
> +                  Missiles and Break blocks with Missiles (Expert) and Can Kill Bosses
this specific one is worth a comment mentioning that you're farming missile drops

2024-04-19 21:35 UTC, duncathan approved these changes

2024-04-19 21:45 UTC, merged