Dont hardcode prime 3 export message
randovania/randovania pull request #6480
Opened 2024-05-03 16:51 UTC by Miepee

Should keep the same behaviour as before. Maybe the window is a little bigger, but i dont really care about that.

![grafik](https://github.com/randovania/randovania/assets/38186597/a65762c7-ffe8-4d57-a810-fe1db7e86ab8)

2024-05-04 17:02 UTC, ThanatosGit requested changes
Don't hardcode it, is a good idea.

I don't get why there is the whole game options added with input_path and output_path because nothing is used and required. It all ends up in the `NotImplementedError` and is only for "whenever anyone implements a corruption patcher".... but I still prefer to not add dead code in advance.

2024-05-04 17:03 UTC, Miepee commented
> I don't get why there is the whole game options added with input_path and output_path because nothing is used and required

Cause I copy pasted from Blank Dev Game lol. That's the default implementation basically.

2024-05-10 14:24 UTC, Miepee commented
addresed

2024-05-11 19:23 UTC, ThanatosGit approved these changes

2024-05-11 19:31 UTC, merged