AM2R: Have seperate shuffled and required artifacts
randovania/randovania pull request #6525
Opened 2024-05-12 16:25 UTC by Miepee

![grafik](https://github.com/randovania/randovania/assets/38186597/f60b834a-2041-4097-9e3c-8e8fea085cb4)

2024-05-16 09:51 UTC, henriquegemignani commented
Instead of "is placed", what about "exists" or "can be collected" or some variant?

2024-05-16 10:07 UTC, henriquegemignani requested changes

2024-05-16 12:26 UTC, Miepee commented
Rephrased
![grafik](https://github.com/randovania/randovania/assets/38186597/b248d098-27df-4cc5-90f3-5bc7241ad125)

2024-05-17 19:03 UTC, henriquegemignani approved these changes

2024-05-17 23:42 UTC, merged