Add Factorio
randovania/randovania pull request #6569
Opened 2024-05-20 18:06 UTC by henriquegemignani

Patcher: https://github.com/henriquegemignani/factorio-randovania-mod

Current Features:
- Full logic database, generated from data dumps exported from the game. Requirements have two parts:
   - Arbitrary "tier" for each research which leads to arbitrary requirements for each tier. Intended to provide some QoL research before you're required to automate high volume of things. 
   - Unlocked everything needed to research the necessary science packs
- Random recipe generation for science packs and rocket parts. These recipes are balanced to have a similar cost and complexity of the original recipes.
- Shuffles many of the start items and introduces a burner lab and assembling machine as starting items, to ensure it's always possible to automate science from start.
- Progressive pickups.

Todo (after this PR):
- Settings for tweaking random recipes (disable, only rocket parts, only science packs, maybe difficulty?)
- Better export dialog (find steam installation, find mod folder)
- Pickup pool with more copies of "bonus tech". Potentially balancing the tiers of these.
- Full playtesting and balancing

![image](https://github.com/randovania/randovania/assets/884928/08bd3577-d284-42f9-8fb8-81d81c4305d6)
![image](https://github.com/randovania/randovania/assets/884928/35200ae2-1ddb-4926-8b0c-31e45ac4fa90)
![image](https://github.com/randovania/randovania/assets/884928/7aa997c3-1d5c-4e5e-9619-4f138c301ced)

2024-05-20 18:53 UTC, Miepee commented
tests fail

2024-05-26 15:34 UTC, duncathan requested changes

2024-05-26 15:34 UTC, duncathan commented on randovania/games/factorio/generator/pool_creator.py
> +def create_victory_key(resource_database: ResourceDatabase) -> PickupEntry:
intended?

2024-05-26 15:34 UTC, duncathan commented on randovania/games/factorio/hash_words.py
> +    "Arugula",
proper hash words needed

2024-05-26 15:34 UTC, duncathan commented on randovania/lib/pyeasyga.py
please add a comment indicating the changes made and why we can't use the pypi impl
(or make your own package tbh)

2024-05-26 15:34 UTC, duncathan commented on test/test_files/log_files/factorio/starter_preset.rdvgame
> +                                "num_shuffled_pickups": 1
this appears to be an outdated starter preset. unsure if that's a problem

2024-05-26 17:08 UTC, duncathan approved these changes

2024-05-26 18:09 UTC, merged