Force transport room names on HUD if transport rando is enabled
randovania/randovania pull request #6586
Opened 2024-05-23 23:37 UTC by MayberryZoom

As described in https://github.com/randovania/open-dread-rando/issues/323, this will prevent players from missing out on the large advantage from having room names on HUD enabled with transport rando. This is accomplished by forcing the option in the patcher.json to `ALWAYS` if it is disabled with transport rando, then supplying only the transport room names.

As a result of this PR, the collision camera dictionary will no longer be included in the patcher.json unless room names on HUD or transport rando is enabled.

Requires open-dread-rando to be bumped before merging.

2024-05-24 20:46 UTC, Miepee reviewed
mypy is complaining, otherwise this looks fine to me. Don't think fixing mypy here is that easy due to how cosmetic_dict is structured.

2024-05-25 08:37 UTC, Miepee reviewed
Since this PR is about changed behaviour on transport rando, can you add at least one more elevator rando file with the cosmetic option set to either FADE or ALWAYS?

2024-05-25 11:44 UTC, henriquegemignani requested changes
Other than these comment, looks good.

2024-05-25 11:44 UTC, henriquegemignani commented on randovania/games/dread/exporter/patch_data_factory.py
> +    def _build_teleporter_name_dict(self, cc_dict: dict = {}) -> dict[str, dict[str, str]]:
First, don't ever use mutable objects as default arguments. The default argument is shared between all calls and it's not recreated for every call, for fun(tm) bugs.

Second, let's not have this argument.

2024-05-25 11:44 UTC, henriquegemignani commented on randovania/games/dread/exporter/patch_data_factory.py
> +        return self._build_teleporter_name_dict(all_dict)
Merge the result of `_build_teleporter_name_dict` into the all_dict here

2024-05-25 20:01 UTC, henriquegemignani approved these changes

2024-05-25 20:16 UTC, merged