Support pickups with multiple original locations
randovania/randovania pull request #6649
Opened 2024-05-29 17:15 UTC by henriquegemignani

2024-05-30 07:26 UTC, ThanatosGit requested changes
lgtm. Can be implemented later for the other games.

2024-05-30 07:26 UTC, ThanatosGit commented on CHANGELOG.md
> +- Added: Progressives pickups can now be configured to be placed vanilla.
It's `Progressive pickups` and not `ProgessiveS pickups`, isn't it?

2024-05-30 08:05 UTC, Miepee commented
Do you want to get that in before the june release?

2024-06-01 22:31 UTC, toasterparty commented
Does this mean you could put all missiles, power bomb expansions, etanks, etc. to their vanilla locations? I feel like that would finally end the confusion as to what exactly "major/minor" means by letting the user configure it themselves instead of checking a box.

2024-06-01 22:47 UTC, duncathan commented
> I feel like that would finally end the confusion as to what exactly "major/minor" means by letting the user configure it themselves instead of checking a box.

I'm not sure what you mean here?

2024-06-01 23:53 UTC, henriquegemignani commented
> Does this mean you could put all missiles, power bomb expansions, etanks, etc. to their vanilla locations? I feel like that would finally end the confusion as to what exactly "major/minor" means by letting the user configure it themselves instead of checking a box.

AmmoPickupDefinition don't support this actually. And the later part has nothing to do with this feature.

2024-06-02 00:04 UTC, toasterparty commented
What I'm saying is if `AmmoPickupDefinition` did support this, then you can replace the major/minor functionality with this because they are functionally equivalent.

2024-06-02 00:11 UTC, henriquegemignani commented
No? This is just assigning certain pickups to an specific location when creating the pool. It doesn't even touch the generator, like major/minor does.

2024-06-02 00:23 UTC, duncathan commented
> What I'm saying is if `AmmoPickupDefinition` did support this, then you can replace the major/minor functionality with this because they are functionally equivalent.

I still don't follow. What exactly would be replaced? And for what purpose? I'm confused what this PR is supposed to have to do with major/minor

2024-06-10 09:56 UTC, ThanatosGit commented on CHANGELOG.md
> +- Added: Progressives pickups can now be configured to be placed vanilla.
It's just the changelog and ready to go?

2024-06-10 19:25 UTC, ThanatosGit approved these changes

2024-06-10 20:54 UTC, merged