Allow 'Open Map' cosmetic option for Prime to be enabled with Random Elevators
randovania/randovania pull request #6676
Opened 2024-06-06 18:21 UTC by Nystrata

The reasoning for disabling the 'Open Map' cosmetic for Prime 1 for Elevator Randomizer was that players supposedly could just look at the room name to see the Elevator destination.  
However, in Prime 1, room names don't appear for not-visited rooms, even after using a Map Station .  
Unless there are plans for a patch that shows room names for not-visited rooms, players should be allowed to use Open Map regardless of whether elevators are randomized or not.  

* Visited Room (Name is revealed)
  * ![image](https://github.com/randovania/randovania/assets/15365192/56755439-9510-45ca-a8b3-b9577c448bcd)
* Not-visited Room (Name is not revealed)
  * ![image](https://github.com/randovania/randovania/assets/15365192/be60c83b-3417-4f6b-b056-f92fa37a3b82)

2024-06-06 18:23 UTC, henriquegemignani commented
No for me. It's very intentional that we don't let that go. Randomprime needs to not reveal the elevator rooms when elevator rando is enabled, but it doesn't offer that afaik.

2024-06-06 18:26 UTC, duncathan commented
> No for me. It's very intentional that we don't let that go. Randomprime needs to not reveal the elevator rooms when elevator rando is enabled, but it doesn't offer that afaik.

afaict the point Nyss is making is that room names are not currently revealed *at all* until they've been visited, unlike the behavior in echoes

2024-06-06 18:29 UTC, Nystrata commented
> > No for me. It's very intentional that we don't let that go. Randomprime needs to not reveal the elevator rooms when elevator rando is enabled, but it doesn't offer that afaik.
> 
> afaict the point Nyss is making is that room names are not currently revealed _at all_ until they've been visited, unlike the behavior in echoes

Yes, this is what I mean

2024-06-06 18:30 UTC, toasterparty approved these changes
I don't remember who was doing the map patcher stuff in the first place

2024-06-06 18:34 UTC, duncathan requested changes
changelog entry

2024-06-06 18:34 UTC, henriquegemignani commented
> > No for me. It's very intentional that we don't let that go. Randomprime needs to not reveal the elevator rooms when elevator rando is enabled, but it doesn't offer that afaik.
> 
> afaict the point Nyss is making is that room names are not currently revealed _at all_ until they've been visited, unlike the behavior in echoes

I know. Between spoiling the elevator destinations and not revealing the map, my choice is not revealing the map. I'm firmly opposed to spoiling the elevator destinations.

2024-06-06 18:37 UTC, Nystrata commented
> I know. Between spoiling the elevator destinations and not revealing the map, my choice is not revealing the map. I'm firmly opposed to spoiling the elevator destinations.

My point is that,   
In Echoes, Open Map shows room shapes and room names  
In Prime, Open Map shows *only room shapes* and does not show room names   
If you look at the first post, you can see that in the screenshots - enabling Open Map for Prime 1 *does not reveal elevator destinations*, it only reveals the shapes of the rooms and item dots

2024-06-06 18:38 UTC, duncathan commented
yeah nobody is advocating for spoiling the destinations. that'd be a non-starter for mii as well

2024-06-06 18:39 UTC, henriquegemignani commented
If revealing the map does not show room names for Prime 1, then that's a regression for Prime 1. A long time ago that was working.

2024-06-06 18:41 UTC, JeffGainsNGames commented
> If revealing the map does not show room names for Prime 1, then that's a regression for Prime 1. A long time ago that was working.

iirc it's been like this since ~5.0.0 at least

2024-06-06 18:50 UTC, Nystrata commented
Oh huh,
I wasn't aware revealed map names was a feature in earlier versions

2024-06-06 18:50 UTC, henriquegemignani commented
![image](https://github.com/randovania/randovania/assets/884928/98688741-7764-4f9f-938d-71a6cfccd20a)
It works in 3.0.3

2024-06-14 06:24 UTC, ThanatosGit commented
What's the conclusion? Should not visited rooms show the room name or should this one here be merged?
The later would require to fix the tests. (I know they are flaky but given that all of them are failing, I guess there is so something to fix).

2024-06-17 02:37 UTC, closed without merging