Add typing to resolver
randovania/randovania pull request #6723
Opened 2024-06-16 16:53 UTC by Miepee

Also fixes #6328

2024-06-16 18:38 UTC, henriquegemignani commented on randovania/resolver/resolver.py
> +        additional = frozenset()
wrong, it gets modified just below

2024-06-16 18:40 UTC, henriquegemignani commented on randovania/resolver/bootstrap.py
> +    ) -> ResourceGain | dict:
One or the other please

2024-06-16 18:51 UTC, henriquegemignani requested changes

2024-06-16 18:51 UTC, henriquegemignani commented on randovania/layout/base/base_configuration.py
> +    energy_per_tank: int
I don't feel this is enough to justify this intermediate base class.

2024-06-26 10:47 UTC, ThanatosGit commented
@Miepee  *ping* 😀

2025-02-02 17:55 UTC, closed without merging