Make vanilla progressives for am2r and MSR too
randovania/randovania pull request #6846
Opened 2024-07-03 16:42 UTC by Miepee

I thought these were added when they got added for dread and echoes. apparently not.

2024-07-03 17:22 UTC, ThanatosGit requested changes
And please no new features on release day :p

2024-07-03 17:22 UTC, ThanatosGit commented on CHANGELOG.md
> +- Progressive pickups can now be configured to be placed vanilla.
Missing `Added`

2024-07-03 17:22 UTC, ThanatosGit commented on CHANGELOG.md
> +- Progressive pickups can now be configured to be placed vanilla.
Same

2024-07-03 17:33 UTC, Miepee commented
> And please no new features on release day :p

For me this is less a new feature, and more  "fix what the original PR was supposed to do".  
But almost no one plays with vanilla items so I'm fine waiting another month. (Even if they do, they still have a workaround)

2024-07-03 18:02 UTC, henriquegemignani commented
Even if the original PR intended for this, it just means the reason won't have the feature then.

2024-07-04 15:13 UTC, dyceron approved these changes

2024-07-04 15:25 UTC, merged