Door Lock Rando: Find either side of door
randovania/randovania pull request #7229
Opened 2024-09-15 12:21 UTC by Tyranisaur

Instead of looking for only one of the sides of each door, look for either side. This leads to fewer impossible results, which should speed up generation. However, there's a risk that seeds could be less interesting, due to always finding the most accessible side of the door.

2024-09-15 13:45 UTC, duncathan requested changes
this should be behind an experimental generator setting, since it poses the risk of being less interesting

2024-10-29 21:57 UTC, duncathan requested changes
being that this is an experimental setting, is there any reason not to include in the upcoming release?

2024-10-29 21:57 UTC, duncathan commented on CHANGELOG.md
> +- Added: Option that changes Door Lock Rando so that when determining which types a door can be randomized into, the algorithm searches for either side of the door using the resolver. This means some
please indicate that it's an experimental option, since otherwise users may be confused why they can't find it

2024-10-29 22:07 UTC, Miepee commented
> is there any reason not to include in the upcoming release?

By the time this would get merged, it'd be like 1.5 days before the new release, which feels a little too close to comfort for my tastes

2024-11-02 02:25 UTC, Miepee approved these changes

2024-11-02 02:25 UTC, Miepee commented
@Tyranisaur merge conflicting right now.

2024-11-04 19:59 UTC, merged