Refactor dialogs
randovania/randovania pull request #7258
Opened 2024-09-24 18:31 UTC by ThanatosGit

2024-09-24 18:57 UTC, Miepee commented on randovania/gui/widgets/game_connection_window.py
> +            return
it's not. it returns the button that was clicked, and on the warning prompt we usually dont care about what button was clicked as there's only "ok" to choose from.

2024-09-24 19:02 UTC, henriquegemignani commented on randovania/gui/widgets/game_connection_window.py
> -            builder.connector_window.show()
Yes, keep a reference so it's not lost.

2024-10-06 16:33 UTC, henriquegemignani requested changes

2024-10-06 16:33 UTC, henriquegemignani commented on randovania/gui/widgets/game_connection_window.py
> +        if session_id:
I feel that not having a session id for a session you're trying to login is a considerable severe error that shouldn't be just ignored. It's kinda of "the button should have been disabled instead" kind of situation, so maybe this should just assert.

2024-10-06 16:33 UTC, henriquegemignani commented on randovania/games/common/gui/connector_prompt_dialog.py
> +        super().__init__(**kwargs)
Can you add some tests for this class?

2024-10-07 07:27 UTC, henriquegemignani requested changes
Oh, since you added type hints please add the file to the list in pyproject.toml so mypy becomes required for it.

2024-10-08 18:56 UTC, henriquegemignani commented
> > Oh, since you added type hints please add the file to the list in pyproject.toml so mypy becomes required for it.
> 
> How do I make mypy not complain about the keyword arguments? I changed it to `Any` for now. According to this https://stackoverflow.com/a/63550734/6459327 `Unpack` and a `TypedDict` could be added but if I use a `TypedDict`, I could just directly declare all parameters in the `__init__` params instead.

Declaring all the parameters in the `__init__` is the better API IMO because then it's clear what the possible args are.
You can also just expose only the parameters we're actually using in the code right now too.

2024-10-10 08:36 UTC, henriquegemignani approved these changes

2024-10-10 10:19 UTC, merged