Prime: weighting changes
randovania/randovania pull request #7418
Opened 2024-10-21 17:56 UTC by JeffGainsNGames

Data: <https://docs.google.com/spreadsheets/d/1M3-d1ICg_FBMSZjYUSe8BBpKuJDbScUylH_eGzxX1YU/edit?usp=sharing>

2024-10-21 18:01 UTC, Miepee reviewed
this needs a changelog entry

2024-10-21 18:19 UTC, JeffGainsNGames commented
> Unless you disagree that a user will not notice in regular gameplay...

I would argue this, since people "notice" things all the time that may even be incorrect. However if there's a precedent happy to take that.

2024-10-23 19:21 UTC, toasterparty requested changes

2024-10-23 19:21 UTC, toasterparty commented on CHANGELOG.md
> +- Changed: Artifact, Phazon Suit, and Missile Expansion weighting adjusted to improve distribution of Artifacts away from certain high probability locations.
```suggestion
- Changed: Artifact, Phazon Suit, and Missile Expansion generation weights adjusted resulting in more even item-location probability distribution.
```

2024-10-25 22:56 UTC, merged